for(var i=0; i<10; i++) {
    
    for(var j=0; j<10; j++) {
        document.write(nuevoArray[i][j]);
    }
}
//SOFKI BOT MATRIZ RECTANGULAR 
//SALTA A CASILLA ADYACENTE A VERTICAL O HORIZONTAL

//ENTRADAS TABLERO , MATRIZ RECTANGULAR DE ENTERO LLENA DEL 0 AL 9, LA CANTIDAD DE FILAS Y COLUMNAS , PUEDE IR DE 1 A 300.
//POS INICIAL 
//POS FINAL

//SALIDA

